In [ ]:
import pandas as pd


In [2]:
import numpy as np

In [3]:
import tensorflow as tf

In [7]:
ratings_df = pd.read_csv('main/ml-latest-small/ratings.csv')

In [8]:
ratings_df.tail()

userId  movieId  rating   timestamp
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

In [9]:
movies_df = pd.read_csv('main/ml-latest-small/movies.csv')

In [10]:
movies_df.tail()

movieId                                      title  \
9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   193583               No Game No Life: Zero (2017)   
9739   193585                               Flint (2017)   
9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                               genres  
9737  Action|Animation|Comedy|Fantasy  
9738         Animation|Comedy|Fantasy  
9739                            Drama  
9740                 Action|Animation  
9741                           Comedy

In [11]:
movies_df['movieRow'] = movies_df.index

In [12]:
movies_df.tail()

movieId                                      title  \
9737   193581  Black Butler: Book of the Atlantic (2017)   
9738   193583               No Game No Life: Zero (2017)   
9739   193585                               Flint (2017)   
9740   193587        Bungo Stray Dogs: Dead Apple (2018)   
9741   193609        Andrew Dice Clay: Dice Rules (1991)   

                               genres  movieRow  
9737  Action|Animation|Comedy|Fantasy      9737  
9738         Animation|Comedy|Fantasy      9738  
9739                            Drama      9739  
9740                 Action|Animation      9740  
9741                           Comedy      9741

In [13]:
movies_df = movies_df[['movieRow', 'movieId', 'title']]

In [14]:
movies_df.tail()

movieRow  movieId                                      title
9737      9737   193581  Black Butler: Book of the Atlantic (2017)
9738      9738   193583               No Game No Life: Zero (2017)
9739      9739   193585                               Flint (2017)
9740      9740   193587        Bungo Stray Dogs: Dead Apple (2018)
9741      9741   193609        Andrew Dice Clay: Dice Rules (1991)

In [15]:
movies_df.to_csv('moviesProcessed.csv', index = False, header = True, encoding='utf-8')

In [16]:
ratings_df = pd.merge(ratings_df, movies_df, on='movieId')

In [17]:
ratings_df.head()

userId  movieId  rating   timestamp  movieRow             title
0       1        1     4.0   964982703         0  Toy Story (1995)
1       5        1     4.0   847434962         0  Toy Story (1995)
2       7        1     4.5  1106635946         0  Toy Story (1995)
3      15        1     2.5  1510577970         0  Toy Story (1995)
4      17        1     4.5  1305696483         0  Toy Story (1995)

In [18]:
ratings_df = ratings_df[['userId', 'movieRow', 'rating']]

In [19]:
ratings_df.tail()

userId  movieRow  rating
100831     610      9325     2.5
100832     610      9330     4.5
100833     610      9342     3.0
100834     610      9389     3.5
100835     610      9390     3.5

In [20]:
ratings_df.to_csv('ratingsProcessed.csv', index = False, header = True, encoding='utf-8')

In [21]:
ratings_df.head()

userId  movieRow  rating
0       1         0     4.0
1       5         0     4.0
2       7         0     4.5
3      15         0     2.5
4      17         0     4.5

In [22]:
usersNo = ratings_df['userId'].max() + 1

In [23]:
moviesNo = movies_df['movieId'].max() + 1

In [24]:
rating = np.zeros((moviesNo, usersNo))

In [25]:
flag = 0
ratings_df_length = np.shape(ratings_df)[0]
for index, row in ratings_df.iterrows():
    rating[int(row['movieRow']), int(row['userId'])] = row['rating']
    flag += 1

In [26]:
record = rating > 0

In [27]:
record

array([[False,  True, False, ...,  True,  True,  True],
       [False, False, False, ...,  True, False, False],
       [False,  True, False, ...,  True, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [28]:
record = np.array(record, dtype = int)

In [48]:
def normalize_ratings(rating, record):
    m, n = rating.shape
    rating_mean = np.zeros((m, 1))
    rating_norm = np.zeros((m, n))
    for i in range(m):
        idx = record[i, :] != 0
        rating_mean[i] = np.mean(rating[i, idx])
        rating_norm[i, idx] -= rating_mean[i]
    return rating_norm, rating_mean

In [50]:
rating_norm, rating_mean = normalize_ratings(rating, record)

In [31]:
arr = np.array([[1,2],[3,4],[5,6]])

In [41]:
rating_mean = np.nan_to_num(rating_mean)
rating_norm = np.nan_to_num(rating_norm)

In [42]:
np.nan_to_num(rating_mean)

array([[3.92093023],
       [3.43181818],
       [3.25961538],
       ...,
       [0.        ],
       [0.        ],
       [0.        ]])

In [43]:
np.mean([1, 2, 3])

2.0

In [44]:
arr[0, [False, True]]

array([2])

In [45]:
rating_norm

array([[ 0.        , -3.92093023,  0.        , ..., -3.92093023,
        -3.92093023, -3.92093023],
       [ 0.        ,  0.        ,  0.        , ..., -3.43181818,
         0.        ,  0.        ],
       [ 0.        , -3.25961538,  0.        , ..., -3.25961538,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [46]:
rating_mean

array([[3.92093023],
       [3.43181818],
       [3.25961538],
       ...,
       [0.        ],
       [0.        ],
       [0.        ]])

In [51]:
rating_norm

array([[ 0.        , -3.92093023,  0.        , ..., -3.92093023,
        -3.92093023, -3.92093023],
       [ 0.        ,  0.        ,  0.        , ..., -3.43181818,
         0.        ,  0.        ],
       [ 0.        , -3.25961538,  0.        , ..., -3.25961538,
         0.        ,  0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [52]:
num_features = 10

In [54]:
X_parameters = tf.Variable(tf.random_normal([moviesNo, num_features], stddev=0.35))

In [55]:
Theta_parameters = tf.Variable(tf.random_normal([usersNo, num_features], stddev=0.35))

In [58]:
if 

TypeError: argument of type 'NoneType' is not iterable